#!/usr/bin/env python3
"""Extract TeX macros from .sty/.tex/.py sources for Quarto MathJax slides."""

from __future__ import annotations

import argparse
import ast
import re
from pathlib import Path

MACRO_KEYS = (
    "\\newcommand",
    "\\renewcommand",
    "\\providecommand",
    "\\DeclareMathOperator",
    "\\DeclareRobustCommand",
)
DECL_OP_RE = re.compile(r"\\DeclareMathOperator(\*)?\s*\{\\([A-Za-z@]+)\}\s*\{(.+)\}\s*$")


def strip_latex_comment(line: str) -> str:
    out = []
    escaped = False
    for ch in line:
        if ch == "%" and not escaped:
            break
        out.append(ch)
        escaped = (ch == "\\") and not escaped
        if ch != "\\":
            escaped = False
    return "".join(out).strip()


def parse_python_string_literals(source_text: str) -> list[str]:
    """Return all literal string nodes from a Python module."""
    try:
        tree = ast.parse(source_text)
    except SyntaxError:
        return []

    strings: list[str] = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Constant) and isinstance(node.value, str):
            strings.append(node.value)
    return strings


def convert_declare_math_operator(line: str) -> str:
    m = DECL_OP_RE.match(line)
    if not m:
        return line
    star, macro_name, body = m.groups()
    operator = r"\operatorname*" if star else r"\operatorname"
    return rf"\newcommand{{\{macro_name}}}{{{operator}{{{body}}}}}"


def normalize_macro_line(line: str) -> str:
    line = strip_latex_comment(line)
    if not line:
        return ""
    if line.startswith(r"\usepackage") or line.startswith(r"\RequirePackage"):
        return ""
    if line.startswith(r"\newtheorem") or line.startswith(r"\newenvironment"):
        return ""
    if line.startswith(r"\let"):
        return ""
    if not any(line.startswith(key) for key in MACRO_KEYS) and not line.startswith("\\def\\"):
        return ""

    line = convert_declare_math_operator(line)
    line = line.replace(r"\DeclareRobustCommand", r"\newcommand", 1)
    line = line.replace(r"\providecommand", r"\newcommand", 1)
    line = line.replace(r"\ensuremath", "")
    line = line.replace(r"\boondoxupr", r"\mathscr")
    line = line.replace(r"\xspace", "")
    return line.strip()


def extract_macros_from_text(text: str) -> list[str]:
    macros: list[str] = []
    for raw_line in text.splitlines():
        normalized = normalize_macro_line(raw_line)
        if normalized:
            macros.append(normalized)
    return macros


def extract_macros_from_source(path: Path) -> list[str]:
    text = path.read_text(encoding="utf-8")
    macros = extract_macros_from_text(text)

    if path.suffix == ".py":
        for literal in parse_python_string_literals(text):
            macros.extend(extract_macros_from_text(literal))

    seen = set()
    ordered = []
    for macro in macros:
        if macro not in seen:
            seen.add(macro)
            ordered.append(macro)
    return ordered


def write_quarto_include(macros: list[str], sources: list[Path], output: Path, add_fallbacks: bool) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open("w", encoding="utf-8") as f:
        f.write("<!-- Auto-generated by scripts/generate_math_macros.py -->\n")
        f.write("<!-- Sources: " + ", ".join(str(source) for source in sources) + " -->\n")
        f.write('<div style="display:none" aria-hidden="true">\n')
        f.write("$$\n")
        if add_fallbacks:
            f.write(r"\newcommand{\bm}[1]{\boldsymbol{#1}}" + "\n")
            f.write(r"\newcommand{\bbone}{\mathbf{1}}" + "\n")
            f.write(r"\newcommand{\boondoxupr}[1]{\mathscr{#1}}" + "\n")
        for macro in macros:
            f.write(macro + "\n")
        f.write("$$\n")
        f.write("</div>\n")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate a Quarto include file with MathJax macro definitions."
    )
    parser.add_argument(
        "sources",
        nargs="+",
        help="Source files with macro definitions (.sty, .tex, or .py).",
    )
    parser.add_argument(
        "--output",
        default="presentations/styles/presentation-macros.html",
        help="Output include file path (default: %(default)s).",
    )
    parser.add_argument(
        "--no-fallbacks",
        action="store_true",
        help="Disable fallback definitions for \\bm/\\bbone/\\boondoxupr.",
    )
    args = parser.parse_args()

    source_paths = [Path(source) for source in args.sources]
    output_value = args.output

    # Backward compatibility with older form:
    #   python generate_math_macros.py input.sty output.html
    if (
        output_value == "presentations/styles/presentation-macros.html"
        and len(source_paths) >= 2
        and source_paths[-1].suffix in {".html", ".htm"}
    ):
        output_value = str(source_paths[-1])
        source_paths = source_paths[:-1]

    missing = [str(path) for path in source_paths if not path.exists()]
    if missing:
        raise SystemExit("Missing source file(s): " + ", ".join(missing))

    all_macros: list[str] = []
    for source in source_paths:
        all_macros.extend(extract_macros_from_source(source))

    seen = set()
    deduped: list[str] = []
    for macro in all_macros:
        if macro not in seen:
            seen.add(macro)
            deduped.append(macro)

    out_path = Path(output_value)
    write_quarto_include(
        deduped,
        source_paths,
        out_path,
        add_fallbacks=not args.no_fallbacks,
    )
    print(f"Wrote {len(deduped)} macro definitions to {out_path}")


if __name__ == "__main__":
    main()
